<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Page</title>
    <link rel="stylesheet" href="/header.css">
    <link rel="stylesheet" href="/about.css">


</head>
<body>
     <section id="header">
        <h1 id="title">Hunterpedia</h1>

        <div id="search">
            <input type="text" id="search-input" placeholder="Search for a Hunter...">
            <button id="search-button">Search</button>
        </div>

        <div id="logo">
            <img src="/images/Hunter-x-Hunter-Emblem.png" alt="Hunter x Hunter Logo" width="100">
        </div>

    </section>

    <section id="nav">
        <nav>
            <ul>
                <li><a href="/index.html">Home</a></li>
                <li><a href="/details.html">Details</a></li>
                <li><a href="/about.html">Learn More</a></li>
                <li><a href="/new-character-form.html">Add a Hunter</a></li>
            </ul>
        </nav>
    </section>

    <h2>Welcome to the Hunterpedia!</h2>
    <section class="container" id="main">
        <p>Hunter x Hunter is basically what happens when you mix friendship, wild powers, and emotional damage into one iconic anime 🍃⚡
            <br>
        It follows Gon, a super-optimistic kid on a mission to become a Hunter and find his deadbeat-but-legendary dad. Along the way, he teams up with an assassin bestie, a revenge-driven scholar, and a walking embodiment of chaos, and together they face exams, monsters, villains who did <strong>not</strong> need to go that hard, and a power system (Nen) that’s way deeper than it looks.
            <br>
        It starts fun and adventurous… then slowly hits you with moral dilemmas, heartbreak, and moments that pull on your heart strings. Cute one minute, unhinged the next — <strong>Hunter x Hunter</strong> is a trap and fans love it</p>
            <br>
    <img src="/images/license.png" alt="Hunter x Hunter Logo" width="200">

    </section>
</body>
</html>