<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Character Details</title>
    <link rel="stylesheet" href="/details.css">

</head>
<body>
     <section id="header">
        <h1 id="title">Hunterpedia</h1>

        <div id="search">
            <input type="text" id="search-input" placeholder="Search for a Hunter...">
            <button id="search-button">Search</button>
        </div>

        <div id="logo">
            <img src="/images/Hunter-x-Hunter-Emblem.png" alt="Hunter x Hunter Logo" width="100">
        </div>

    </section>

    <section id="nav">
        <nav>
            <ul>
                <li><a href="/index.html">Home</a></li>
                <li><a href="/details.html">Details</a></li>
                <li><a href="/about.html">Learn More</a></li>
                <li><a href="/new-character-form.html">Add a Hunter</a></li>
            </ul>
        </nav>
    </section>

    <section class="container" id="main">
        <div class="license-card">
            <img src="images/killua.png" alt="Killua Zoldyck" width="150">
            <h2 id="character-name">Killua Zoldyck</h2>
        </div>
        
        <h3 id="abilities">Abilities</h3>
        <ul id="ability-list">
            <li>Expert Assassin Techniques</li>
            <li>Superhuman Agility and Reflexes</li>
            <li>Electricity Manipulation (Godspeed)</li>
            <li>Stealth and Infiltration Skills</li>
            <li>Skilled Hand-to-Hand Combatant</li>
        </ul>

        <p id="background-info">${hunter.backgroundInfo}</p> 

            <br>    


</body>
</html>